package com.acmeplex.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Column;
import java.util.Date;
import java.util.List;

@Entity
public class Receipt {

    /*
     * Primary key of the Receipt table
     * The value of id will be automatically generated by the database when a new Receipt entity is created
     */
    @Id
    private Long id;

    /*
     * payment column of the Receipt table
     * The payment corresponds to the payment made for the ticket purchase
     */
    @ManyToOne
    private Payment payment;

    /*
     * user column of the Receipt table
     * The user who made the payment (the customer)
     */
    @ManyToOne
    private User user;

    /*
     * movie column of the Receipt table
     * The movie that the user has purchased tickets for
     */
    @ManyToOne
    private Movie movie;

    /*
     * showtime column of the Receipt table
     * The showtime when the user will watch the movie
     */
    @ManyToOne
    private Showtime showtime;

    /*
     * seats column of the Receipt table
     * List of seats reserved by the user for the movie
     */
    @OneToMany
    private List<Seat> seats;

    /*
     * totalAmount column of the Receipt table
     * The total amount paid for the tickets
     */
    @Column(nullable = false)
    private double totalAmount;

    /*
     * calculationDate column of the Receipt table
     * The date when the receipt was generated
     */
    @Column(nullable = false)
    private Date calculationDate;

    /*
     * Default constructor
     * Hibernate requires a no-arg constructor for JPA entities
     */
    public Receipt() {}

    /*
     * Parameterized constructor
     */
    public Receipt(Payment payment, User user, Movie movie, Showtime showtime, List<Seat> seats, double totalAmount, Date calculationDate) {
        this.payment = payment;
        this.user = user;
        this.movie = movie;
        this.showtime = showtime;
        this.seats = seats;
        this.totalAmount = totalAmount;
        this.calculationDate = calculationDate;
    }

    /*
     * Method to generate the receipt
     * This is just a placeholder for actual business logic
     */
    public void generateReceipt() {
        System.out.println("Generating receipt for " + user.getFirstName() + " " + user.getLastName());
    }

    /*
     * Method to send the receipt to the user
     * This is just a placeholder for actual business logic
     */
    public void sendReceipt() {
        System.out.println("Sending receipt to " + user.getEmail());
    }

    /*
     * Getters and setters
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Payment getPayment() {
        return payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    public Showtime getShowtime() {
        return showtime;
    }

    public void setShowtime(Showtime showtime) {
        this.showtime = showtime;
    }

    public List<Seat> getSeats() {
        return seats;
    }

    public void setSeats(List<Seat> seats) {
        this.seats = seats;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Date getCalculationDate() {
        return calculationDate;
    }

    public void setCalculationDate(Date calculationDate) {
        this.calculationDate = calculationDate;
    }

    /*
     * Override toString() for better object representation
     */
    @Override
    public String toString() {
        return "Receipt{id=" + id + ", payment=" + payment + ", user=" + user + ", movie=" + movie +
                ", showtime=" + showtime + ", seats=" + seats + ", totalAmount=" + totalAmount + 
                ", calculationDate=" + calculationDate + "}";
    }
}
