package com.acmeplex.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import javax.persistence.Column;

@Entity
public class Seat {

    /*
     * Primary key of the Seat table
     * The value of id will be automatically generated by the database when a new Seat entity is created
     */
    @Id
    private Long id;

    /*
     * seatNumber column of the Seat table
     * The seat number is a unique identifier for the seat within a theater
     */
    private int seatNumber;

    /*
     * row column of the Seat table
     * The row refers to the seat's position in the theater's seating arrangement
     */
    @Column(nullable = false)
    private int row;

    /*
     * available column of the Seat table
     * Indicates whether the seat is available for booking (true = available, false = reserved)
     */
    @Column(nullable = false)
    private boolean available;

    /*
     * Many-to-one relationship with the Showtime entity
     * Each Seat is associated with one Showtime
     */
    @ManyToOne
    @JoinColumn(name = "showtime_id", nullable = false)
    private Showtime showtime;

    /*
     * Default constructor
     * Hibernate requires a no-arg constructor for JPA entities
     */
    public Seat() {}

    /*
     * Parameterized constructor
     */
    public Seat(int seatNumber, int row, boolean available, Showtime showtime) {
        this.seatNumber = seatNumber;
        this.row = row;
        this.available = available;
        this.showtime = showtime;
    }

    /*
     * Method to reserve the seat
     * Marks the seat as reserved (unavailable)
     */
    public void reserveSeat() {
        this.available = false;
    }

    /*
     * Method to release the seat
     * Marks the seat as available again
     */
    public void releaseSeat() {
        this.available = true;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSeatNumber() {
        return seatNumber;
    }

    public void setSeatNumber(int seatNumber) {
        this.seatNumber = seatNumber;
    }

    public int getRow() {
        return row;
    }

    public void setRow(int row) {
        this.row = row;
    }

    public boolean isAvailable() {
        return available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    public Showtime getShowtime() {
        return showtime;
    }

    public void setShowtime(Showtime showtime) {
        this.showtime = showtime;
    }

    /*
     * Override toString() for better object representation
     */
    @Override
    public String toString() {
        return "Seat{id=" + id + ", seatNumber=" + seatNumber + ", row=" + row + ", available=" + available + ", showtime=" + showtime + "}";
    }
}
