package com.acmeplex.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import javax.persistence.Column;
import java.util.Date;

@Entity
public class Ticket {

    /*
     * Primary key of the Ticket table
     * The value of id will be automatically generated by the database when a new Ticket entity is created
     */
    @Id
    private Long id;

    /*
     * price column of the Ticket table
     * The price of the ticket
     */
    @Column(nullable = false)
    private double price;

    /*
     * status column of the Ticket table
     * The status of the ticket (e.g., "Booked", "Cancelled", "Refunded")
     */
    @Column(nullable = false, length = 50)
    private String status;

    /*
     * purchaseDate column of the Ticket table
     * The date when the ticket was purchased
     */
    @Column(nullable = false)
    private Date purchaseDate;

    /*
     * Many-to-one relationship with the Showtime entity
     * A ticket is associated with one Showtime
     */
    @ManyToOne
    @JoinColumn(name = "showtime_id", nullable = false)
    private Showtime showtime;

    /*
     * Many-to-one relationship with the Seat entity
     * A ticket is associated with one Seat
     */
    @ManyToOne
    @JoinColumn(name = "seat_id", nullable = false)
    private Seat seat;

    /*
     * Many-to-one relationship with the Payment entity
     * A ticket is associated with one Payment
     */
    @ManyToOne
    @JoinColumn(name = "payment_id", nullable = false)
    private Payment payment;

    /*
     * Many-to-one relationship with the Movie entity
     * A ticket is associated with one Movie
     */
    @ManyToOne
    @JoinColumn(name = "movie_id", nullable = false)
    private Movie movie;

    /*
     * Default constructor
     * Hibernate requires a no-arg constructor for JPA entities
     */
    public Ticket() {}

    /*
     * Parameterized constructor
     */
    public Ticket(double price, String status, Date purchaseDate, Showtime showtime, Seat seat, Payment payment, Movie movie) {
        this.price = price;
        this.status = status;
        this.purchaseDate = purchaseDate;
        this.showtime = showtime;
        this.seat = seat;
        this.payment = payment;
        this.movie = movie;
    }

    /*
     * Method to cancel the ticket
     * Changes the status of the ticket to "Cancelled"
     */
    public void cancelTicket() {
        this.status = "Cancelled";
    }

    /*
     * Method to apply a refund for the ticket
     * Changes the status to "Refunded"
     */
    public void applyRefund() {
        this.status = "Refunded";
    }

    /*
     * Method to get details about the ticket
     * Returns the ticket details as a string
     */
    public String getTicketDetails() {
        return "Ticket Details: [ID: " + id + ", Price: " + price + ", Status: " + status + ", Showtime: " + showtime.getId() 
               + ", Seat: " + seat.getSeatNumber() + ", Movie: " + movie.getTitle() + "]";
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getPurchaseDate() {
        return purchaseDate;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public Showtime getShowtime() {
        return showtime;
    }

    public void setShowtime(Showtime showtime) {
        this.showtime = showtime;
    }

    public Seat getSeat() {
        return seat;
    }

    public void setSeat(Seat seat) {
        this.seat = seat;
    }

    public Payment getPayment() {
        return payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    /*
     * Override toString() for better object representation
     */
    @Override
    public String toString() {
        return "Ticket{id=" + id + ", price=" + price + ", status='" + status + "', purchaseDate=" + purchaseDate + ", showtime=" + showtime + ", seat=" + seat + ", movie=" + movie + "}";
    }
}
